# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/com.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/com.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/com.proto\x12\x06module\"\"\n\x0fRequestToModule\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x1d\n\x0bModuleReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2L\n\rCommunication\x12;\n\tGetAReply\x12\x17.module.RequestToModule\x1a\x13.module.ModuleReply\"\x00\x42.Z,github.com/somuthink/pics_journal/core/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.com_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/somuthink/pics_journal/core/proto'
  _globals['_REQUESTTOMODULE']._serialized_start=27
  _globals['_REQUESTTOMODULE']._serialized_end=61
  _globals['_MODULEREPLY']._serialized_start=63
  _globals['_MODULEREPLY']._serialized_end=92
  _globals['_COMMUNICATION']._serialized_start=94
  _globals['_COMMUNICATION']._serialized_end=170
# @@protoc_insertion_point(module_scope)
